/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppChangePasswordRouteImport } from './routes/_app/change-password'
import { Route as AppPermissionsRouteImport } from './routes/_app/permissions'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppSystemSettingsRouteImport } from './routes/_app/system-settings'
import { Route as AppTestRouteImport } from './routes/_app/test'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicImpersonationRouteImport } from './routes/_public/impersonation'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppDashboardAccountingOverviewRouteImport } from './routes/_app/dashboard/accounting-overview'
import { Route as AppDashboardAddBatchRouteImport } from './routes/_app/dashboard/add-batch'
import { Route as AppDashboardAddInventoryTransactionRouteImport } from './routes/_app/dashboard/add-inventory-transaction'
import { Route as AppDashboardAddProductRouteImport } from './routes/_app/dashboard/add-product'
import { Route as AppDashboardAddSaleRouteImport } from './routes/_app/dashboard/add-sale'
import { Route as AppDashboardAlertsRouteImport } from './routes/_app/dashboard/alerts'
import { Route as AppDashboardApiKeysRouteImport } from './routes/_app/dashboard/api-keys'
import { Route as AppDashboardAppsRouteImport } from './routes/_app/dashboard/apps'
import { Route as AppDashboardBrandsRouteImport } from './routes/_app/dashboard/brands'
import { Route as AppDashboardCategoriesRouteImport } from './routes/_app/dashboard/categories'
import { Route as AppDashboardCitiesRouteImport } from './routes/_app/dashboard/cities'
import { Route as AppDashboardCompanyRouteImport } from './routes/_app/dashboard/company'
import { Route as AppDashboardConfirmationOverviewRouteImport } from './routes/_app/dashboard/confirmation-overview'
import { Route as AppDashboardConsignmentVendorsRouteImport } from './routes/_app/dashboard/consignment-vendors'
import { Route as AppDashboardCouponsRouteImport } from './routes/_app/dashboard/coupons'
import { Route as AppDashboardCustomersRouteImport } from './routes/_app/dashboard/customers'
import { Route as AppDashboardDeficitsAlertRouteImport } from './routes/_app/dashboard/deficits-alert'
import { Route as AppDashboardDirectoryRouteImport } from './routes/_app/dashboard/directory'
import { Route as AppDashboardFulfillmentListsRouteImport } from './routes/_app/dashboard/fulfillment-lists'
import { Route as AppDashboardGovernoratesRouteImport } from './routes/_app/dashboard/governorates'
import { Route as AppDashboardIntegrationsRouteImport } from './routes/_app/dashboard/integrations'
import { Route as AppDashboardInventoryAdjustmentRouteImport } from './routes/_app/dashboard/inventory-adjustment'
import { Route as AppDashboardInventoryOverviewRouteImport } from './routes/_app/dashboard/inventory-overview'
import { Route as AppDashboardInventoryTransactionsRouteImport } from './routes/_app/dashboard/inventory-transactions'
import { Route as AppDashboardInventoryTransfersRouteImport } from './routes/_app/dashboard/inventory-transfers'
import { Route as AppDashboardLowStockRouteImport } from './routes/_app/dashboard/low-stock'
import { Route as AppDashboardOperationTypesRouteImport } from './routes/_app/dashboard/operation-types'
import { Route as AppDashboardOrderSourcesRouteImport } from './routes/_app/dashboard/order-sources'
import { Route as AppDashboardOrdersRouteImport } from './routes/_app/dashboard/orders'
import { Route as AppDashboardOrdersTransactionsRouteImport } from './routes/_app/dashboard/orders-transactions'
import { Route as AppDashboardPackingListRouteImport } from './routes/_app/dashboard/packing-list'
import { Route as AppDashboardPaymentMethodsRouteImport } from './routes/_app/dashboard/payment-methods'
import { Route as AppDashboardPickingListRouteImport } from './routes/_app/dashboard/picking-list'
import { Route as AppDashboardProductFamilyRouteImport } from './routes/_app/dashboard/product-family'
import { Route as AppDashboardProductStocksRouteImport } from './routes/_app/dashboard/product-stocks'
import { Route as AppDashboardProductionRouteImport } from './routes/_app/dashboard/production'
import { Route as AppDashboardProductsRouteImport } from './routes/_app/dashboard/products'
import { Route as AppDashboardPurchaseOrdersRouteImport } from './routes/_app/dashboard/purchase-orders'
import { Route as AppDashboardPurchaseTransactionsRouteImport } from './routes/_app/dashboard/purchase-transactions'
import { Route as AppDashboardReasonsRouteImport } from './routes/_app/dashboard/reasons'
import { Route as AppDashboardReportsRouteImport } from './routes/_app/dashboard/reports'
import { Route as AppDashboardReturnsRouteImport } from './routes/_app/dashboard/returns'
import { Route as AppDashboardSalesOverviewRouteImport } from './routes/_app/dashboard/sales-overview'
import { Route as AppDashboardScannerTransactionsRouteImport } from './routes/_app/dashboard/scanner-transactions'
import { Route as AppDashboardScanningRouteImport } from './routes/_app/dashboard/scanning'
import { Route as AppDashboardShippingCompaniesRouteImport } from './routes/_app/dashboard/shipping-companies'
import { Route as AppDashboardShippingOverviewRouteImport } from './routes/_app/dashboard/shipping-overview'
import { Route as AppDashboardShippingReturnsRouteImport } from './routes/_app/dashboard/shipping-returns'
import { Route as AppDashboardStockCountsRouteImport } from './routes/_app/dashboard/stock-counts'
import { Route as AppDashboardStockOperationsRouteImport } from './routes/_app/dashboard/stock-operations'
import { Route as AppDashboardStorageLocationsRouteImport } from './routes/_app/dashboard/storage-locations'
import { Route as AppDashboardStoresRouteImport } from './routes/_app/dashboard/stores'
import { Route as AppDashboardSupplierOverviewRouteImport } from './routes/_app/dashboard/supplier-overview'
import { Route as AppDashboardSyncErrorsRouteImport } from './routes/_app/dashboard/sync-errors'
import { Route as AppDashboardUomRouteImport } from './routes/_app/dashboard/uom'
import { Route as AppDashboardVendorsRouteImport } from './routes/_app/dashboard/vendors'
import { Route as AppDashboardWarehousesRouteImport } from './routes/_app/dashboard/warehouses'
import { Route as PlatformPlatformIndexRouteImport } from './routes/_platform/platform/index'
import { Route as PlatformPlatformCompaniesRouteImport } from './routes/_platform/platform/companies'
import { Route as AppDashboardReportsLocationsRouteImport } from './routes/_app/dashboard/reports/locations'
import { Route as AppDashboardReportsStockRouteImport } from './routes/_app/dashboard/reports/stock'
import { Route as ApiPublicProxySplatRouteImport } from './routes/api/public/proxy/$'
import { Route as AppDashboardOrdersOrderIdInvoiceRouteImport } from './routes/_app/dashboard/orders/$orderId/invoice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSystemSettingsRoute = AppSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestRoute = AppTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicImpersonationRoute = PublicImpersonationRouteImport.update({
  id: '/impersonation',
  path: '/impersonation',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardAccountingOverviewRoute =
  AppDashboardAccountingOverviewRouteImport.update({
    id: '/dashboard/accounting-overview',
    path: '/dashboard/accounting-overview',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardAddBatchRoute = AppDashboardAddBatchRouteImport.update({
  id: '/dashboard/add-batch',
  path: '/dashboard/add-batch',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardAddInventoryTransactionRoute =
  AppDashboardAddInventoryTransactionRouteImport.update({
    id: '/dashboard/add-inventory-transaction',
    path: '/dashboard/add-inventory-transaction',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardAddProductRoute = AppDashboardAddProductRouteImport.update({
  id: '/dashboard/add-product',
  path: '/dashboard/add-product',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardAddSaleRoute = AppDashboardAddSaleRouteImport.update({
  id: '/dashboard/add-sale',
  path: '/dashboard/add-sale',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardAlertsRoute = AppDashboardAlertsRouteImport.update({
  id: '/dashboard/alerts',
  path: '/dashboard/alerts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardApiKeysRoute = AppDashboardApiKeysRouteImport.update({
  id: '/dashboard/api-keys',
  path: '/dashboard/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardAppsRoute = AppDashboardAppsRouteImport.update({
  id: '/dashboard/apps',
  path: '/dashboard/apps',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardBrandsRoute = AppDashboardBrandsRouteImport.update({
  id: '/dashboard/brands',
  path: '/dashboard/brands',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardCategoriesRoute = AppDashboardCategoriesRouteImport.update({
  id: '/dashboard/categories',
  path: '/dashboard/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardCitiesRoute = AppDashboardCitiesRouteImport.update({
  id: '/dashboard/cities',
  path: '/dashboard/cities',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardCompanyRoute = AppDashboardCompanyRouteImport.update({
  id: '/dashboard/company',
  path: '/dashboard/company',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardConfirmationOverviewRoute =
  AppDashboardConfirmationOverviewRouteImport.update({
    id: '/dashboard/confirmation-overview',
    path: '/dashboard/confirmation-overview',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardConsignmentVendorsRoute =
  AppDashboardConsignmentVendorsRouteImport.update({
    id: '/dashboard/consignment-vendors',
    path: '/dashboard/consignment-vendors',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardCouponsRoute = AppDashboardCouponsRouteImport.update({
  id: '/dashboard/coupons',
  path: '/dashboard/coupons',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardCustomersRoute = AppDashboardCustomersRouteImport.update({
  id: '/dashboard/customers',
  path: '/dashboard/customers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardDeficitsAlertRoute =
  AppDashboardDeficitsAlertRouteImport.update({
    id: '/dashboard/deficits-alert',
    path: '/dashboard/deficits-alert',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardDirectoryRoute = AppDashboardDirectoryRouteImport.update({
  id: '/dashboard/directory',
  path: '/dashboard/directory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardFulfillmentListsRoute =
  AppDashboardFulfillmentListsRouteImport.update({
    id: '/dashboard/fulfillment-lists',
    path: '/dashboard/fulfillment-lists',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardGovernoratesRoute =
  AppDashboardGovernoratesRouteImport.update({
    id: '/dashboard/governorates',
    path: '/dashboard/governorates',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardIntegrationsRoute =
  AppDashboardIntegrationsRouteImport.update({
    id: '/dashboard/integrations',
    path: '/dashboard/integrations',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardInventoryAdjustmentRoute =
  AppDashboardInventoryAdjustmentRouteImport.update({
    id: '/dashboard/inventory-adjustment',
    path: '/dashboard/inventory-adjustment',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardInventoryOverviewRoute =
  AppDashboardInventoryOverviewRouteImport.update({
    id: '/dashboard/inventory-overview',
    path: '/dashboard/inventory-overview',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardInventoryTransactionsRoute =
  AppDashboardInventoryTransactionsRouteImport.update({
    id: '/dashboard/inventory-transactions',
    path: '/dashboard/inventory-transactions',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardInventoryTransfersRoute =
  AppDashboardInventoryTransfersRouteImport.update({
    id: '/dashboard/inventory-transfers',
    path: '/dashboard/inventory-transfers',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardLowStockRoute = AppDashboardLowStockRouteImport.update({
  id: '/dashboard/low-stock',
  path: '/dashboard/low-stock',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardOperationTypesRoute =
  AppDashboardOperationTypesRouteImport.update({
    id: '/dashboard/operation-types',
    path: '/dashboard/operation-types',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardOrderSourcesRoute =
  AppDashboardOrderSourcesRouteImport.update({
    id: '/dashboard/order-sources',
    path: '/dashboard/order-sources',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardOrdersRoute = AppDashboardOrdersRouteImport.update({
  id: '/dashboard/orders',
  path: '/dashboard/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardOrdersTransactionsRoute =
  AppDashboardOrdersTransactionsRouteImport.update({
    id: '/dashboard/orders-transactions',
    path: '/dashboard/orders-transactions',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardPackingListRoute = AppDashboardPackingListRouteImport.update({
  id: '/dashboard/packing-list',
  path: '/dashboard/packing-list',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardPaymentMethodsRoute =
  AppDashboardPaymentMethodsRouteImport.update({
    id: '/dashboard/payment-methods',
    path: '/dashboard/payment-methods',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardPickingListRoute = AppDashboardPickingListRouteImport.update({
  id: '/dashboard/picking-list',
  path: '/dashboard/picking-list',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardProductFamilyRoute =
  AppDashboardProductFamilyRouteImport.update({
    id: '/dashboard/product-family',
    path: '/dashboard/product-family',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardProductStocksRoute =
  AppDashboardProductStocksRouteImport.update({
    id: '/dashboard/product-stocks',
    path: '/dashboard/product-stocks',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardProductionRoute = AppDashboardProductionRouteImport.update({
  id: '/dashboard/production',
  path: '/dashboard/production',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardProductsRoute = AppDashboardProductsRouteImport.update({
  id: '/dashboard/products',
  path: '/dashboard/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardPurchaseOrdersRoute =
  AppDashboardPurchaseOrdersRouteImport.update({
    id: '/dashboard/purchase-orders',
    path: '/dashboard/purchase-orders',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardPurchaseTransactionsRoute =
  AppDashboardPurchaseTransactionsRouteImport.update({
    id: '/dashboard/purchase-transactions',
    path: '/dashboard/purchase-transactions',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardReasonsRoute = AppDashboardReasonsRouteImport.update({
  id: '/dashboard/reasons',
  path: '/dashboard/reasons',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardReportsRoute = AppDashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardReturnsRoute = AppDashboardReturnsRouteImport.update({
  id: '/dashboard/returns',
  path: '/dashboard/returns',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardSalesOverviewRoute =
  AppDashboardSalesOverviewRouteImport.update({
    id: '/dashboard/sales-overview',
    path: '/dashboard/sales-overview',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardScannerTransactionsRoute =
  AppDashboardScannerTransactionsRouteImport.update({
    id: '/dashboard/scanner-transactions',
    path: '/dashboard/scanner-transactions',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardScanningRoute = AppDashboardScanningRouteImport.update({
  id: '/dashboard/scanning',
  path: '/dashboard/scanning',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardShippingCompaniesRoute =
  AppDashboardShippingCompaniesRouteImport.update({
    id: '/dashboard/shipping-companies',
    path: '/dashboard/shipping-companies',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardShippingOverviewRoute =
  AppDashboardShippingOverviewRouteImport.update({
    id: '/dashboard/shipping-overview',
    path: '/dashboard/shipping-overview',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardShippingReturnsRoute =
  AppDashboardShippingReturnsRouteImport.update({
    id: '/dashboard/shipping-returns',
    path: '/dashboard/shipping-returns',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardStockCountsRoute = AppDashboardStockCountsRouteImport.update({
  id: '/dashboard/stock-counts',
  path: '/dashboard/stock-counts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardStockOperationsRoute =
  AppDashboardStockOperationsRouteImport.update({
    id: '/dashboard/stock-operations',
    path: '/dashboard/stock-operations',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardStorageLocationsRoute =
  AppDashboardStorageLocationsRouteImport.update({
    id: '/dashboard/storage-locations',
    path: '/dashboard/storage-locations',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardStoresRoute = AppDashboardStoresRouteImport.update({
  id: '/dashboard/stores',
  path: '/dashboard/stores',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardSupplierOverviewRoute =
  AppDashboardSupplierOverviewRouteImport.update({
    id: '/dashboard/supplier-overview',
    path: '/dashboard/supplier-overview',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardSyncErrorsRoute = AppDashboardSyncErrorsRouteImport.update({
  id: '/dashboard/sync-errors',
  path: '/dashboard/sync-errors',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardUomRoute = AppDashboardUomRouteImport.update({
  id: '/dashboard/uom',
  path: '/dashboard/uom',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardVendorsRoute = AppDashboardVendorsRouteImport.update({
  id: '/dashboard/vendors',
  path: '/dashboard/vendors',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardWarehousesRoute = AppDashboardWarehousesRouteImport.update({
  id: '/dashboard/warehouses',
  path: '/dashboard/warehouses',
  getParentRoute: () => AppRouteRoute,
} as any)
const PlatformPlatformIndexRoute = PlatformPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPlatformCompaniesRoute =
  PlatformPlatformCompaniesRouteImport.update({
    id: '/platform/companies',
    path: '/platform/companies',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const AppDashboardReportsLocationsRoute =
  AppDashboardReportsLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AppDashboardReportsRoute,
  } as any)
const AppDashboardReportsStockRoute =
  AppDashboardReportsStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AppDashboardReportsRoute,
  } as any)
const ApiPublicProxySplatRoute = ApiPublicProxySplatRouteImport.update({
  id: '/api/public/proxy/$',
  path: '/api/public/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardOrdersOrderIdInvoiceRoute =
  AppDashboardOrdersOrderIdInvoiceRouteImport.update({
    id: '/$orderId/invoice',
    path: '/$orderId/invoice',
    getParentRoute: () => AppDashboardOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/access': typeof AppAccessRoute
  '/change-password': typeof AppChangePasswordRoute
  '/permissions': typeof AppPermissionsRoute
  '/roles': typeof AppRolesRoute
  '/system-settings': typeof AppSystemSettingsRoute
  '/test': typeof AppTestRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/impersonation': typeof PublicImpersonationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/dashboard/accounting-overview': typeof AppDashboardAccountingOverviewRoute
  '/dashboard/add-batch': typeof AppDashboardAddBatchRoute
  '/dashboard/add-inventory-transaction': typeof AppDashboardAddInventoryTransactionRoute
  '/dashboard/add-product': typeof AppDashboardAddProductRoute
  '/dashboard/add-sale': typeof AppDashboardAddSaleRoute
  '/dashboard/alerts': typeof AppDashboardAlertsRoute
  '/dashboard/api-keys': typeof AppDashboardApiKeysRoute
  '/dashboard/apps': typeof AppDashboardAppsRoute
  '/dashboard/brands': typeof AppDashboardBrandsRoute
  '/dashboard/categories': typeof AppDashboardCategoriesRoute
  '/dashboard/cities': typeof AppDashboardCitiesRoute
  '/dashboard/company': typeof AppDashboardCompanyRoute
  '/dashboard/confirmation-overview': typeof AppDashboardConfirmationOverviewRoute
  '/dashboard/consignment-vendors': typeof AppDashboardConsignmentVendorsRoute
  '/dashboard/coupons': typeof AppDashboardCouponsRoute
  '/dashboard/customers': typeof AppDashboardCustomersRoute
  '/dashboard/deficits-alert': typeof AppDashboardDeficitsAlertRoute
  '/dashboard/directory': typeof AppDashboardDirectoryRoute
  '/dashboard/fulfillment-lists': typeof AppDashboardFulfillmentListsRoute
  '/dashboard/governorates': typeof AppDashboardGovernoratesRoute
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/inventory-adjustment': typeof AppDashboardInventoryAdjustmentRoute
  '/dashboard/inventory-overview': typeof AppDashboardInventoryOverviewRoute
  '/dashboard/inventory-transactions': typeof AppDashboardInventoryTransactionsRoute
  '/dashboard/inventory-transfers': typeof AppDashboardInventoryTransfersRoute
  '/dashboard/low-stock': typeof AppDashboardLowStockRoute
  '/dashboard/operation-types': typeof AppDashboardOperationTypesRoute
  '/dashboard/order-sources': typeof AppDashboardOrderSourcesRoute
  '/dashboard/orders': typeof AppDashboardOrdersRouteWithChildren
  '/dashboard/orders-transactions': typeof AppDashboardOrdersTransactionsRoute
  '/dashboard/packing-list': typeof AppDashboardPackingListRoute
  '/dashboard/payment-methods': typeof AppDashboardPaymentMethodsRoute
  '/dashboard/picking-list': typeof AppDashboardPickingListRoute
  '/dashboard/product-family': typeof AppDashboardProductFamilyRoute
  '/dashboard/product-stocks': typeof AppDashboardProductStocksRoute
  '/dashboard/production': typeof AppDashboardProductionRoute
  '/dashboard/products': typeof AppDashboardProductsRoute
  '/dashboard/purchase-orders': typeof AppDashboardPurchaseOrdersRoute
  '/dashboard/purchase-transactions': typeof AppDashboardPurchaseTransactionsRoute
  '/dashboard/reasons': typeof AppDashboardReasonsRoute
  '/dashboard/reports': typeof AppDashboardReportsRouteWithChildren
  '/dashboard/returns': typeof AppDashboardReturnsRoute
  '/dashboard/sales-overview': typeof AppDashboardSalesOverviewRoute
  '/dashboard/scanner-transactions': typeof AppDashboardScannerTransactionsRoute
  '/dashboard/scanning': typeof AppDashboardScanningRoute
  '/dashboard/shipping-companies': typeof AppDashboardShippingCompaniesRoute
  '/dashboard/shipping-overview': typeof AppDashboardShippingOverviewRoute
  '/dashboard/shipping-returns': typeof AppDashboardShippingReturnsRoute
  '/dashboard/stock-counts': typeof AppDashboardStockCountsRoute
  '/dashboard/stock-operations': typeof AppDashboardStockOperationsRoute
  '/dashboard/storage-locations': typeof AppDashboardStorageLocationsRoute
  '/dashboard/stores': typeof AppDashboardStoresRoute
  '/dashboard/supplier-overview': typeof AppDashboardSupplierOverviewRoute
  '/dashboard/sync-errors': typeof AppDashboardSyncErrorsRoute
  '/dashboard/uom': typeof AppDashboardUomRoute
  '/dashboard/vendors': typeof AppDashboardVendorsRoute
  '/dashboard/warehouses': typeof AppDashboardWarehousesRoute
  '/platform/companies': typeof PlatformPlatformCompaniesRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/platform/': typeof PlatformPlatformIndexRoute
  '/dashboard/reports/locations': typeof AppDashboardReportsLocationsRoute
  '/dashboard/reports/stock': typeof AppDashboardReportsStockRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
  '/dashboard/orders/$orderId/invoice': typeof AppDashboardOrdersOrderIdInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/access': typeof AppAccessRoute
  '/change-password': typeof AppChangePasswordRoute
  '/permissions': typeof AppPermissionsRoute
  '/roles': typeof AppRolesRoute
  '/system-settings': typeof AppSystemSettingsRoute
  '/test': typeof AppTestRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/impersonation': typeof PublicImpersonationRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/dashboard/accounting-overview': typeof AppDashboardAccountingOverviewRoute
  '/dashboard/add-batch': typeof AppDashboardAddBatchRoute
  '/dashboard/add-inventory-transaction': typeof AppDashboardAddInventoryTransactionRoute
  '/dashboard/add-product': typeof AppDashboardAddProductRoute
  '/dashboard/add-sale': typeof AppDashboardAddSaleRoute
  '/dashboard/alerts': typeof AppDashboardAlertsRoute
  '/dashboard/api-keys': typeof AppDashboardApiKeysRoute
  '/dashboard/apps': typeof AppDashboardAppsRoute
  '/dashboard/brands': typeof AppDashboardBrandsRoute
  '/dashboard/categories': typeof AppDashboardCategoriesRoute
  '/dashboard/cities': typeof AppDashboardCitiesRoute
  '/dashboard/company': typeof AppDashboardCompanyRoute
  '/dashboard/confirmation-overview': typeof AppDashboardConfirmationOverviewRoute
  '/dashboard/consignment-vendors': typeof AppDashboardConsignmentVendorsRoute
  '/dashboard/coupons': typeof AppDashboardCouponsRoute
  '/dashboard/customers': typeof AppDashboardCustomersRoute
  '/dashboard/deficits-alert': typeof AppDashboardDeficitsAlertRoute
  '/dashboard/directory': typeof AppDashboardDirectoryRoute
  '/dashboard/fulfillment-lists': typeof AppDashboardFulfillmentListsRoute
  '/dashboard/governorates': typeof AppDashboardGovernoratesRoute
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/inventory-adjustment': typeof AppDashboardInventoryAdjustmentRoute
  '/dashboard/inventory-overview': typeof AppDashboardInventoryOverviewRoute
  '/dashboard/inventory-transactions': typeof AppDashboardInventoryTransactionsRoute
  '/dashboard/inventory-transfers': typeof AppDashboardInventoryTransfersRoute
  '/dashboard/low-stock': typeof AppDashboardLowStockRoute
  '/dashboard/operation-types': typeof AppDashboardOperationTypesRoute
  '/dashboard/order-sources': typeof AppDashboardOrderSourcesRoute
  '/dashboard/orders': typeof AppDashboardOrdersRouteWithChildren
  '/dashboard/orders-transactions': typeof AppDashboardOrdersTransactionsRoute
  '/dashboard/packing-list': typeof AppDashboardPackingListRoute
  '/dashboard/payment-methods': typeof AppDashboardPaymentMethodsRoute
  '/dashboard/picking-list': typeof AppDashboardPickingListRoute
  '/dashboard/product-family': typeof AppDashboardProductFamilyRoute
  '/dashboard/product-stocks': typeof AppDashboardProductStocksRoute
  '/dashboard/production': typeof AppDashboardProductionRoute
  '/dashboard/products': typeof AppDashboardProductsRoute
  '/dashboard/purchase-orders': typeof AppDashboardPurchaseOrdersRoute
  '/dashboard/purchase-transactions': typeof AppDashboardPurchaseTransactionsRoute
  '/dashboard/reasons': typeof AppDashboardReasonsRoute
  '/dashboard/reports': typeof AppDashboardReportsRouteWithChildren
  '/dashboard/returns': typeof AppDashboardReturnsRoute
  '/dashboard/sales-overview': typeof AppDashboardSalesOverviewRoute
  '/dashboard/scanner-transactions': typeof AppDashboardScannerTransactionsRoute
  '/dashboard/scanning': typeof AppDashboardScanningRoute
  '/dashboard/shipping-companies': typeof AppDashboardShippingCompaniesRoute
  '/dashboard/shipping-overview': typeof AppDashboardShippingOverviewRoute
  '/dashboard/shipping-returns': typeof AppDashboardShippingReturnsRoute
  '/dashboard/stock-counts': typeof AppDashboardStockCountsRoute
  '/dashboard/stock-operations': typeof AppDashboardStockOperationsRoute
  '/dashboard/storage-locations': typeof AppDashboardStorageLocationsRoute
  '/dashboard/stores': typeof AppDashboardStoresRoute
  '/dashboard/supplier-overview': typeof AppDashboardSupplierOverviewRoute
  '/dashboard/sync-errors': typeof AppDashboardSyncErrorsRoute
  '/dashboard/uom': typeof AppDashboardUomRoute
  '/dashboard/vendors': typeof AppDashboardVendorsRoute
  '/dashboard/warehouses': typeof AppDashboardWarehousesRoute
  '/platform/companies': typeof PlatformPlatformCompaniesRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/platform': typeof PlatformPlatformIndexRoute
  '/dashboard/reports/locations': typeof AppDashboardReportsLocationsRoute
  '/dashboard/reports/stock': typeof AppDashboardReportsStockRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
  '/dashboard/orders/$orderId/invoice': typeof AppDashboardOrdersOrderIdInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/change-password': typeof AppChangePasswordRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/system-settings': typeof AppSystemSettingsRoute
  '/_app/test': typeof AppTestRoute
  '/_app/users': typeof AppUsersRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/impersonation': typeof PublicImpersonationRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_app/dashboard/accounting-overview': typeof AppDashboardAccountingOverviewRoute
  '/_app/dashboard/add-batch': typeof AppDashboardAddBatchRoute
  '/_app/dashboard/add-inventory-transaction': typeof AppDashboardAddInventoryTransactionRoute
  '/_app/dashboard/add-product': typeof AppDashboardAddProductRoute
  '/_app/dashboard/add-sale': typeof AppDashboardAddSaleRoute
  '/_app/dashboard/alerts': typeof AppDashboardAlertsRoute
  '/_app/dashboard/api-keys': typeof AppDashboardApiKeysRoute
  '/_app/dashboard/apps': typeof AppDashboardAppsRoute
  '/_app/dashboard/brands': typeof AppDashboardBrandsRoute
  '/_app/dashboard/categories': typeof AppDashboardCategoriesRoute
  '/_app/dashboard/cities': typeof AppDashboardCitiesRoute
  '/_app/dashboard/company': typeof AppDashboardCompanyRoute
  '/_app/dashboard/confirmation-overview': typeof AppDashboardConfirmationOverviewRoute
  '/_app/dashboard/consignment-vendors': typeof AppDashboardConsignmentVendorsRoute
  '/_app/dashboard/coupons': typeof AppDashboardCouponsRoute
  '/_app/dashboard/customers': typeof AppDashboardCustomersRoute
  '/_app/dashboard/deficits-alert': typeof AppDashboardDeficitsAlertRoute
  '/_app/dashboard/directory': typeof AppDashboardDirectoryRoute
  '/_app/dashboard/fulfillment-lists': typeof AppDashboardFulfillmentListsRoute
  '/_app/dashboard/governorates': typeof AppDashboardGovernoratesRoute
  '/_app/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/_app/dashboard/inventory-adjustment': typeof AppDashboardInventoryAdjustmentRoute
  '/_app/dashboard/inventory-overview': typeof AppDashboardInventoryOverviewRoute
  '/_app/dashboard/inventory-transactions': typeof AppDashboardInventoryTransactionsRoute
  '/_app/dashboard/inventory-transfers': typeof AppDashboardInventoryTransfersRoute
  '/_app/dashboard/low-stock': typeof AppDashboardLowStockRoute
  '/_app/dashboard/operation-types': typeof AppDashboardOperationTypesRoute
  '/_app/dashboard/order-sources': typeof AppDashboardOrderSourcesRoute
  '/_app/dashboard/orders': typeof AppDashboardOrdersRouteWithChildren
  '/_app/dashboard/orders-transactions': typeof AppDashboardOrdersTransactionsRoute
  '/_app/dashboard/packing-list': typeof AppDashboardPackingListRoute
  '/_app/dashboard/payment-methods': typeof AppDashboardPaymentMethodsRoute
  '/_app/dashboard/picking-list': typeof AppDashboardPickingListRoute
  '/_app/dashboard/product-family': typeof AppDashboardProductFamilyRoute
  '/_app/dashboard/product-stocks': typeof AppDashboardProductStocksRoute
  '/_app/dashboard/production': typeof AppDashboardProductionRoute
  '/_app/dashboard/products': typeof AppDashboardProductsRoute
  '/_app/dashboard/purchase-orders': typeof AppDashboardPurchaseOrdersRoute
  '/_app/dashboard/purchase-transactions': typeof AppDashboardPurchaseTransactionsRoute
  '/_app/dashboard/reasons': typeof AppDashboardReasonsRoute
  '/_app/dashboard/reports': typeof AppDashboardReportsRouteWithChildren
  '/_app/dashboard/returns': typeof AppDashboardReturnsRoute
  '/_app/dashboard/sales-overview': typeof AppDashboardSalesOverviewRoute
  '/_app/dashboard/scanner-transactions': typeof AppDashboardScannerTransactionsRoute
  '/_app/dashboard/scanning': typeof AppDashboardScanningRoute
  '/_app/dashboard/shipping-companies': typeof AppDashboardShippingCompaniesRoute
  '/_app/dashboard/shipping-overview': typeof AppDashboardShippingOverviewRoute
  '/_app/dashboard/shipping-returns': typeof AppDashboardShippingReturnsRoute
  '/_app/dashboard/stock-counts': typeof AppDashboardStockCountsRoute
  '/_app/dashboard/stock-operations': typeof AppDashboardStockOperationsRoute
  '/_app/dashboard/storage-locations': typeof AppDashboardStorageLocationsRoute
  '/_app/dashboard/stores': typeof AppDashboardStoresRoute
  '/_app/dashboard/supplier-overview': typeof AppDashboardSupplierOverviewRoute
  '/_app/dashboard/sync-errors': typeof AppDashboardSyncErrorsRoute
  '/_app/dashboard/uom': typeof AppDashboardUomRoute
  '/_app/dashboard/vendors': typeof AppDashboardVendorsRoute
  '/_app/dashboard/warehouses': typeof AppDashboardWarehousesRoute
  '/_platform/platform/companies': typeof PlatformPlatformCompaniesRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_platform/platform/': typeof PlatformPlatformIndexRoute
  '/_app/dashboard/reports/locations': typeof AppDashboardReportsLocationsRoute
  '/_app/dashboard/reports/stock': typeof AppDashboardReportsStockRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
  '/_app/dashboard/orders/$orderId/invoice': typeof AppDashboardOrdersOrderIdInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/access'
    | '/change-password'
    | '/permissions'
    | '/roles'
    | '/system-settings'
    | '/test'
    | '/users'
    | '/forgot-password'
    | '/impersonation'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/dashboard/accounting-overview'
    | '/dashboard/add-batch'
    | '/dashboard/add-inventory-transaction'
    | '/dashboard/add-product'
    | '/dashboard/add-sale'
    | '/dashboard/alerts'
    | '/dashboard/api-keys'
    | '/dashboard/apps'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/cities'
    | '/dashboard/company'
    | '/dashboard/confirmation-overview'
    | '/dashboard/consignment-vendors'
    | '/dashboard/coupons'
    | '/dashboard/customers'
    | '/dashboard/deficits-alert'
    | '/dashboard/directory'
    | '/dashboard/fulfillment-lists'
    | '/dashboard/governorates'
    | '/dashboard/integrations'
    | '/dashboard/inventory-adjustment'
    | '/dashboard/inventory-overview'
    | '/dashboard/inventory-transactions'
    | '/dashboard/inventory-transfers'
    | '/dashboard/low-stock'
    | '/dashboard/operation-types'
    | '/dashboard/order-sources'
    | '/dashboard/orders'
    | '/dashboard/orders-transactions'
    | '/dashboard/packing-list'
    | '/dashboard/payment-methods'
    | '/dashboard/picking-list'
    | '/dashboard/product-family'
    | '/dashboard/product-stocks'
    | '/dashboard/production'
    | '/dashboard/products'
    | '/dashboard/purchase-orders'
    | '/dashboard/purchase-transactions'
    | '/dashboard/reasons'
    | '/dashboard/reports'
    | '/dashboard/returns'
    | '/dashboard/sales-overview'
    | '/dashboard/scanner-transactions'
    | '/dashboard/scanning'
    | '/dashboard/shipping-companies'
    | '/dashboard/shipping-overview'
    | '/dashboard/shipping-returns'
    | '/dashboard/stock-counts'
    | '/dashboard/stock-operations'
    | '/dashboard/storage-locations'
    | '/dashboard/stores'
    | '/dashboard/supplier-overview'
    | '/dashboard/sync-errors'
    | '/dashboard/uom'
    | '/dashboard/vendors'
    | '/dashboard/warehouses'
    | '/platform/companies'
    | '/dashboard/'
    | '/platform/'
    | '/dashboard/reports/locations'
    | '/dashboard/reports/stock'
    | '/api/public/proxy/$'
    | '/dashboard/orders/$orderId/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/access'
    | '/change-password'
    | '/permissions'
    | '/roles'
    | '/system-settings'
    | '/test'
    | '/users'
    | '/forgot-password'
    | '/impersonation'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/dashboard/accounting-overview'
    | '/dashboard/add-batch'
    | '/dashboard/add-inventory-transaction'
    | '/dashboard/add-product'
    | '/dashboard/add-sale'
    | '/dashboard/alerts'
    | '/dashboard/api-keys'
    | '/dashboard/apps'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/cities'
    | '/dashboard/company'
    | '/dashboard/confirmation-overview'
    | '/dashboard/consignment-vendors'
    | '/dashboard/coupons'
    | '/dashboard/customers'
    | '/dashboard/deficits-alert'
    | '/dashboard/directory'
    | '/dashboard/fulfillment-lists'
    | '/dashboard/governorates'
    | '/dashboard/integrations'
    | '/dashboard/inventory-adjustment'
    | '/dashboard/inventory-overview'
    | '/dashboard/inventory-transactions'
    | '/dashboard/inventory-transfers'
    | '/dashboard/low-stock'
    | '/dashboard/operation-types'
    | '/dashboard/order-sources'
    | '/dashboard/orders'
    | '/dashboard/orders-transactions'
    | '/dashboard/packing-list'
    | '/dashboard/payment-methods'
    | '/dashboard/picking-list'
    | '/dashboard/product-family'
    | '/dashboard/product-stocks'
    | '/dashboard/production'
    | '/dashboard/products'
    | '/dashboard/purchase-orders'
    | '/dashboard/purchase-transactions'
    | '/dashboard/reasons'
    | '/dashboard/reports'
    | '/dashboard/returns'
    | '/dashboard/sales-overview'
    | '/dashboard/scanner-transactions'
    | '/dashboard/scanning'
    | '/dashboard/shipping-companies'
    | '/dashboard/shipping-overview'
    | '/dashboard/shipping-returns'
    | '/dashboard/stock-counts'
    | '/dashboard/stock-operations'
    | '/dashboard/storage-locations'
    | '/dashboard/stores'
    | '/dashboard/supplier-overview'
    | '/dashboard/sync-errors'
    | '/dashboard/uom'
    | '/dashboard/vendors'
    | '/dashboard/warehouses'
    | '/platform/companies'
    | '/dashboard'
    | '/platform'
    | '/dashboard/reports/locations'
    | '/dashboard/reports/stock'
    | '/api/public/proxy/$'
    | '/dashboard/orders/$orderId/invoice'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_platform'
    | '/_public'
    | '/$'
    | '/_app/access'
    | '/_app/change-password'
    | '/_app/permissions'
    | '/_app/roles'
    | '/_app/system-settings'
    | '/_app/test'
    | '/_app/users'
    | '/_public/forgot-password'
    | '/_public/impersonation'
    | '/_public/login'
    | '/_public/register'
    | '/_public/reset-password'
    | '/_public/signup'
    | '/_app/dashboard/accounting-overview'
    | '/_app/dashboard/add-batch'
    | '/_app/dashboard/add-inventory-transaction'
    | '/_app/dashboard/add-product'
    | '/_app/dashboard/add-sale'
    | '/_app/dashboard/alerts'
    | '/_app/dashboard/api-keys'
    | '/_app/dashboard/apps'
    | '/_app/dashboard/brands'
    | '/_app/dashboard/categories'
    | '/_app/dashboard/cities'
    | '/_app/dashboard/company'
    | '/_app/dashboard/confirmation-overview'
    | '/_app/dashboard/consignment-vendors'
    | '/_app/dashboard/coupons'
    | '/_app/dashboard/customers'
    | '/_app/dashboard/deficits-alert'
    | '/_app/dashboard/directory'
    | '/_app/dashboard/fulfillment-lists'
    | '/_app/dashboard/governorates'
    | '/_app/dashboard/integrations'
    | '/_app/dashboard/inventory-adjustment'
    | '/_app/dashboard/inventory-overview'
    | '/_app/dashboard/inventory-transactions'
    | '/_app/dashboard/inventory-transfers'
    | '/_app/dashboard/low-stock'
    | '/_app/dashboard/operation-types'
    | '/_app/dashboard/order-sources'
    | '/_app/dashboard/orders'
    | '/_app/dashboard/orders-transactions'
    | '/_app/dashboard/packing-list'
    | '/_app/dashboard/payment-methods'
    | '/_app/dashboard/picking-list'
    | '/_app/dashboard/product-family'
    | '/_app/dashboard/product-stocks'
    | '/_app/dashboard/production'
    | '/_app/dashboard/products'
    | '/_app/dashboard/purchase-orders'
    | '/_app/dashboard/purchase-transactions'
    | '/_app/dashboard/reasons'
    | '/_app/dashboard/reports'
    | '/_app/dashboard/returns'
    | '/_app/dashboard/sales-overview'
    | '/_app/dashboard/scanner-transactions'
    | '/_app/dashboard/scanning'
    | '/_app/dashboard/shipping-companies'
    | '/_app/dashboard/shipping-overview'
    | '/_app/dashboard/shipping-returns'
    | '/_app/dashboard/stock-counts'
    | '/_app/dashboard/stock-operations'
    | '/_app/dashboard/storage-locations'
    | '/_app/dashboard/stores'
    | '/_app/dashboard/supplier-overview'
    | '/_app/dashboard/sync-errors'
    | '/_app/dashboard/uom'
    | '/_app/dashboard/vendors'
    | '/_app/dashboard/warehouses'
    | '/_platform/platform/companies'
    | '/_app/dashboard/'
    | '/_platform/platform/'
    | '/_app/dashboard/reports/locations'
    | '/_app/dashboard/reports/stock'
    | '/api/public/proxy/$'
    | '/_app/dashboard/orders/$orderId/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ApiPublicProxySplatRoute: typeof ApiPublicProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/change-password': {
      id: '/_app/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/system-settings': {
      id: '/_app/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof AppSystemSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/test': {
      id: '/_app/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AppTestRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/impersonation': {
      id: '/_public/impersonation'
      path: '/impersonation'
      fullPath: '/impersonation'
      preLoaderRoute: typeof PublicImpersonationRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/accounting-overview': {
      id: '/_app/dashboard/accounting-overview'
      path: '/dashboard/accounting-overview'
      fullPath: '/dashboard/accounting-overview'
      preLoaderRoute: typeof AppDashboardAccountingOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/add-batch': {
      id: '/_app/dashboard/add-batch'
      path: '/dashboard/add-batch'
      fullPath: '/dashboard/add-batch'
      preLoaderRoute: typeof AppDashboardAddBatchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/add-inventory-transaction': {
      id: '/_app/dashboard/add-inventory-transaction'
      path: '/dashboard/add-inventory-transaction'
      fullPath: '/dashboard/add-inventory-transaction'
      preLoaderRoute: typeof AppDashboardAddInventoryTransactionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/add-product': {
      id: '/_app/dashboard/add-product'
      path: '/dashboard/add-product'
      fullPath: '/dashboard/add-product'
      preLoaderRoute: typeof AppDashboardAddProductRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/add-sale': {
      id: '/_app/dashboard/add-sale'
      path: '/dashboard/add-sale'
      fullPath: '/dashboard/add-sale'
      preLoaderRoute: typeof AppDashboardAddSaleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/alerts': {
      id: '/_app/dashboard/alerts'
      path: '/dashboard/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof AppDashboardAlertsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/api-keys': {
      id: '/_app/dashboard/api-keys'
      path: '/dashboard/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AppDashboardApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/apps': {
      id: '/_app/dashboard/apps'
      path: '/dashboard/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof AppDashboardAppsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/brands': {
      id: '/_app/dashboard/brands'
      path: '/dashboard/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof AppDashboardBrandsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/categories': {
      id: '/_app/dashboard/categories'
      path: '/dashboard/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AppDashboardCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/cities': {
      id: '/_app/dashboard/cities'
      path: '/dashboard/cities'
      fullPath: '/dashboard/cities'
      preLoaderRoute: typeof AppDashboardCitiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/company': {
      id: '/_app/dashboard/company'
      path: '/dashboard/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof AppDashboardCompanyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/confirmation-overview': {
      id: '/_app/dashboard/confirmation-overview'
      path: '/dashboard/confirmation-overview'
      fullPath: '/dashboard/confirmation-overview'
      preLoaderRoute: typeof AppDashboardConfirmationOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/consignment-vendors': {
      id: '/_app/dashboard/consignment-vendors'
      path: '/dashboard/consignment-vendors'
      fullPath: '/dashboard/consignment-vendors'
      preLoaderRoute: typeof AppDashboardConsignmentVendorsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/coupons': {
      id: '/_app/dashboard/coupons'
      path: '/dashboard/coupons'
      fullPath: '/dashboard/coupons'
      preLoaderRoute: typeof AppDashboardCouponsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/customers': {
      id: '/_app/dashboard/customers'
      path: '/dashboard/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof AppDashboardCustomersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/deficits-alert': {
      id: '/_app/dashboard/deficits-alert'
      path: '/dashboard/deficits-alert'
      fullPath: '/dashboard/deficits-alert'
      preLoaderRoute: typeof AppDashboardDeficitsAlertRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/directory': {
      id: '/_app/dashboard/directory'
      path: '/dashboard/directory'
      fullPath: '/dashboard/directory'
      preLoaderRoute: typeof AppDashboardDirectoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/fulfillment-lists': {
      id: '/_app/dashboard/fulfillment-lists'
      path: '/dashboard/fulfillment-lists'
      fullPath: '/dashboard/fulfillment-lists'
      preLoaderRoute: typeof AppDashboardFulfillmentListsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/governorates': {
      id: '/_app/dashboard/governorates'
      path: '/dashboard/governorates'
      fullPath: '/dashboard/governorates'
      preLoaderRoute: typeof AppDashboardGovernoratesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/integrations': {
      id: '/_app/dashboard/integrations'
      path: '/dashboard/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AppDashboardIntegrationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/inventory-adjustment': {
      id: '/_app/dashboard/inventory-adjustment'
      path: '/dashboard/inventory-adjustment'
      fullPath: '/dashboard/inventory-adjustment'
      preLoaderRoute: typeof AppDashboardInventoryAdjustmentRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/inventory-overview': {
      id: '/_app/dashboard/inventory-overview'
      path: '/dashboard/inventory-overview'
      fullPath: '/dashboard/inventory-overview'
      preLoaderRoute: typeof AppDashboardInventoryOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/inventory-transactions': {
      id: '/_app/dashboard/inventory-transactions'
      path: '/dashboard/inventory-transactions'
      fullPath: '/dashboard/inventory-transactions'
      preLoaderRoute: typeof AppDashboardInventoryTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/inventory-transfers': {
      id: '/_app/dashboard/inventory-transfers'
      path: '/dashboard/inventory-transfers'
      fullPath: '/dashboard/inventory-transfers'
      preLoaderRoute: typeof AppDashboardInventoryTransfersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/low-stock': {
      id: '/_app/dashboard/low-stock'
      path: '/dashboard/low-stock'
      fullPath: '/dashboard/low-stock'
      preLoaderRoute: typeof AppDashboardLowStockRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/operation-types': {
      id: '/_app/dashboard/operation-types'
      path: '/dashboard/operation-types'
      fullPath: '/dashboard/operation-types'
      preLoaderRoute: typeof AppDashboardOperationTypesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/order-sources': {
      id: '/_app/dashboard/order-sources'
      path: '/dashboard/order-sources'
      fullPath: '/dashboard/order-sources'
      preLoaderRoute: typeof AppDashboardOrderSourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/orders': {
      id: '/_app/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AppDashboardOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/orders-transactions': {
      id: '/_app/dashboard/orders-transactions'
      path: '/dashboard/orders-transactions'
      fullPath: '/dashboard/orders-transactions'
      preLoaderRoute: typeof AppDashboardOrdersTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/packing-list': {
      id: '/_app/dashboard/packing-list'
      path: '/dashboard/packing-list'
      fullPath: '/dashboard/packing-list'
      preLoaderRoute: typeof AppDashboardPackingListRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/payment-methods': {
      id: '/_app/dashboard/payment-methods'
      path: '/dashboard/payment-methods'
      fullPath: '/dashboard/payment-methods'
      preLoaderRoute: typeof AppDashboardPaymentMethodsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/picking-list': {
      id: '/_app/dashboard/picking-list'
      path: '/dashboard/picking-list'
      fullPath: '/dashboard/picking-list'
      preLoaderRoute: typeof AppDashboardPickingListRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/product-family': {
      id: '/_app/dashboard/product-family'
      path: '/dashboard/product-family'
      fullPath: '/dashboard/product-family'
      preLoaderRoute: typeof AppDashboardProductFamilyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/product-stocks': {
      id: '/_app/dashboard/product-stocks'
      path: '/dashboard/product-stocks'
      fullPath: '/dashboard/product-stocks'
      preLoaderRoute: typeof AppDashboardProductStocksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/production': {
      id: '/_app/dashboard/production'
      path: '/dashboard/production'
      fullPath: '/dashboard/production'
      preLoaderRoute: typeof AppDashboardProductionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/products': {
      id: '/_app/dashboard/products'
      path: '/dashboard/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AppDashboardProductsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/purchase-orders': {
      id: '/_app/dashboard/purchase-orders'
      path: '/dashboard/purchase-orders'
      fullPath: '/dashboard/purchase-orders'
      preLoaderRoute: typeof AppDashboardPurchaseOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/purchase-transactions': {
      id: '/_app/dashboard/purchase-transactions'
      path: '/dashboard/purchase-transactions'
      fullPath: '/dashboard/purchase-transactions'
      preLoaderRoute: typeof AppDashboardPurchaseTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/reasons': {
      id: '/_app/dashboard/reasons'
      path: '/dashboard/reasons'
      fullPath: '/dashboard/reasons'
      preLoaderRoute: typeof AppDashboardReasonsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/reports': {
      id: '/_app/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AppDashboardReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/returns': {
      id: '/_app/dashboard/returns'
      path: '/dashboard/returns'
      fullPath: '/dashboard/returns'
      preLoaderRoute: typeof AppDashboardReturnsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/sales-overview': {
      id: '/_app/dashboard/sales-overview'
      path: '/dashboard/sales-overview'
      fullPath: '/dashboard/sales-overview'
      preLoaderRoute: typeof AppDashboardSalesOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/scanner-transactions': {
      id: '/_app/dashboard/scanner-transactions'
      path: '/dashboard/scanner-transactions'
      fullPath: '/dashboard/scanner-transactions'
      preLoaderRoute: typeof AppDashboardScannerTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/scanning': {
      id: '/_app/dashboard/scanning'
      path: '/dashboard/scanning'
      fullPath: '/dashboard/scanning'
      preLoaderRoute: typeof AppDashboardScanningRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/shipping-companies': {
      id: '/_app/dashboard/shipping-companies'
      path: '/dashboard/shipping-companies'
      fullPath: '/dashboard/shipping-companies'
      preLoaderRoute: typeof AppDashboardShippingCompaniesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/shipping-overview': {
      id: '/_app/dashboard/shipping-overview'
      path: '/dashboard/shipping-overview'
      fullPath: '/dashboard/shipping-overview'
      preLoaderRoute: typeof AppDashboardShippingOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/shipping-returns': {
      id: '/_app/dashboard/shipping-returns'
      path: '/dashboard/shipping-returns'
      fullPath: '/dashboard/shipping-returns'
      preLoaderRoute: typeof AppDashboardShippingReturnsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/stock-counts': {
      id: '/_app/dashboard/stock-counts'
      path: '/dashboard/stock-counts'
      fullPath: '/dashboard/stock-counts'
      preLoaderRoute: typeof AppDashboardStockCountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/stock-operations': {
      id: '/_app/dashboard/stock-operations'
      path: '/dashboard/stock-operations'
      fullPath: '/dashboard/stock-operations'
      preLoaderRoute: typeof AppDashboardStockOperationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/storage-locations': {
      id: '/_app/dashboard/storage-locations'
      path: '/dashboard/storage-locations'
      fullPath: '/dashboard/storage-locations'
      preLoaderRoute: typeof AppDashboardStorageLocationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/stores': {
      id: '/_app/dashboard/stores'
      path: '/dashboard/stores'
      fullPath: '/dashboard/stores'
      preLoaderRoute: typeof AppDashboardStoresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/supplier-overview': {
      id: '/_app/dashboard/supplier-overview'
      path: '/dashboard/supplier-overview'
      fullPath: '/dashboard/supplier-overview'
      preLoaderRoute: typeof AppDashboardSupplierOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/sync-errors': {
      id: '/_app/dashboard/sync-errors'
      path: '/dashboard/sync-errors'
      fullPath: '/dashboard/sync-errors'
      preLoaderRoute: typeof AppDashboardSyncErrorsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/uom': {
      id: '/_app/dashboard/uom'
      path: '/dashboard/uom'
      fullPath: '/dashboard/uom'
      preLoaderRoute: typeof AppDashboardUomRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/vendors': {
      id: '/_app/dashboard/vendors'
      path: '/dashboard/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof AppDashboardVendorsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/warehouses': {
      id: '/_app/dashboard/warehouses'
      path: '/dashboard/warehouses'
      fullPath: '/dashboard/warehouses'
      preLoaderRoute: typeof AppDashboardWarehousesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_platform/platform/': {
      id: '/_platform/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformPlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/platform/companies': {
      id: '/_platform/platform/companies'
      path: '/platform/companies'
      fullPath: '/platform/companies'
      preLoaderRoute: typeof PlatformPlatformCompaniesRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_app/dashboard/reports/locations': {
      id: '/_app/dashboard/reports/locations'
      path: '/locations'
      fullPath: '/dashboard/reports/locations'
      preLoaderRoute: typeof AppDashboardReportsLocationsRouteImport
      parentRoute: typeof AppDashboardReportsRoute
    }
    '/_app/dashboard/reports/stock': {
      id: '/_app/dashboard/reports/stock'
      path: '/stock'
      fullPath: '/dashboard/reports/stock'
      preLoaderRoute: typeof AppDashboardReportsStockRouteImport
      parentRoute: typeof AppDashboardReportsRoute
    }
    '/api/public/proxy/$': {
      id: '/api/public/proxy/$'
      path: '/api/public/proxy/$'
      fullPath: '/api/public/proxy/$'
      preLoaderRoute: typeof ApiPublicProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/orders/$orderId/invoice': {
      id: '/_app/dashboard/orders/$orderId/invoice'
      path: '/$orderId/invoice'
      fullPath: '/dashboard/orders/$orderId/invoice'
      preLoaderRoute: typeof AppDashboardOrdersOrderIdInvoiceRouteImport
      parentRoute: typeof AppDashboardOrdersRoute
    }
  }
}

interface AppDashboardOrdersRouteChildren {
  AppDashboardOrdersOrderIdInvoiceRoute: typeof AppDashboardOrdersOrderIdInvoiceRoute
}

const AppDashboardOrdersRouteChildren: AppDashboardOrdersRouteChildren = {
  AppDashboardOrdersOrderIdInvoiceRoute: AppDashboardOrdersOrderIdInvoiceRoute,
}

const AppDashboardOrdersRouteWithChildren =
  AppDashboardOrdersRoute._addFileChildren(AppDashboardOrdersRouteChildren)

interface AppDashboardReportsRouteChildren {
  AppDashboardReportsLocationsRoute: typeof AppDashboardReportsLocationsRoute
  AppDashboardReportsStockRoute: typeof AppDashboardReportsStockRoute
}

const AppDashboardReportsRouteChildren: AppDashboardReportsRouteChildren = {
  AppDashboardReportsLocationsRoute: AppDashboardReportsLocationsRoute,
  AppDashboardReportsStockRoute: AppDashboardReportsStockRoute,
}

const AppDashboardReportsRouteWithChildren =
  AppDashboardReportsRoute._addFileChildren(AppDashboardReportsRouteChildren)

interface AppRouteRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSystemSettingsRoute: typeof AppSystemSettingsRoute
  AppTestRoute: typeof AppTestRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDashboardAccountingOverviewRoute: typeof AppDashboardAccountingOverviewRoute
  AppDashboardAddBatchRoute: typeof AppDashboardAddBatchRoute
  AppDashboardAddInventoryTransactionRoute: typeof AppDashboardAddInventoryTransactionRoute
  AppDashboardAddProductRoute: typeof AppDashboardAddProductRoute
  AppDashboardAddSaleRoute: typeof AppDashboardAddSaleRoute
  AppDashboardAlertsRoute: typeof AppDashboardAlertsRoute
  AppDashboardApiKeysRoute: typeof AppDashboardApiKeysRoute
  AppDashboardAppsRoute: typeof AppDashboardAppsRoute
  AppDashboardBrandsRoute: typeof AppDashboardBrandsRoute
  AppDashboardCategoriesRoute: typeof AppDashboardCategoriesRoute
  AppDashboardCitiesRoute: typeof AppDashboardCitiesRoute
  AppDashboardCompanyRoute: typeof AppDashboardCompanyRoute
  AppDashboardConfirmationOverviewRoute: typeof AppDashboardConfirmationOverviewRoute
  AppDashboardConsignmentVendorsRoute: typeof AppDashboardConsignmentVendorsRoute
  AppDashboardCouponsRoute: typeof AppDashboardCouponsRoute
  AppDashboardCustomersRoute: typeof AppDashboardCustomersRoute
  AppDashboardDeficitsAlertRoute: typeof AppDashboardDeficitsAlertRoute
  AppDashboardDirectoryRoute: typeof AppDashboardDirectoryRoute
  AppDashboardFulfillmentListsRoute: typeof AppDashboardFulfillmentListsRoute
  AppDashboardGovernoratesRoute: typeof AppDashboardGovernoratesRoute
  AppDashboardIntegrationsRoute: typeof AppDashboardIntegrationsRoute
  AppDashboardInventoryAdjustmentRoute: typeof AppDashboardInventoryAdjustmentRoute
  AppDashboardInventoryOverviewRoute: typeof AppDashboardInventoryOverviewRoute
  AppDashboardInventoryTransactionsRoute: typeof AppDashboardInventoryTransactionsRoute
  AppDashboardInventoryTransfersRoute: typeof AppDashboardInventoryTransfersRoute
  AppDashboardLowStockRoute: typeof AppDashboardLowStockRoute
  AppDashboardOperationTypesRoute: typeof AppDashboardOperationTypesRoute
  AppDashboardOrderSourcesRoute: typeof AppDashboardOrderSourcesRoute
  AppDashboardOrdersRoute: typeof AppDashboardOrdersRouteWithChildren
  AppDashboardOrdersTransactionsRoute: typeof AppDashboardOrdersTransactionsRoute
  AppDashboardPackingListRoute: typeof AppDashboardPackingListRoute
  AppDashboardPaymentMethodsRoute: typeof AppDashboardPaymentMethodsRoute
  AppDashboardPickingListRoute: typeof AppDashboardPickingListRoute
  AppDashboardProductFamilyRoute: typeof AppDashboardProductFamilyRoute
  AppDashboardProductStocksRoute: typeof AppDashboardProductStocksRoute
  AppDashboardProductionRoute: typeof AppDashboardProductionRoute
  AppDashboardProductsRoute: typeof AppDashboardProductsRoute
  AppDashboardPurchaseOrdersRoute: typeof AppDashboardPurchaseOrdersRoute
  AppDashboardPurchaseTransactionsRoute: typeof AppDashboardPurchaseTransactionsRoute
  AppDashboardReasonsRoute: typeof AppDashboardReasonsRoute
  AppDashboardReportsRoute: typeof AppDashboardReportsRouteWithChildren
  AppDashboardReturnsRoute: typeof AppDashboardReturnsRoute
  AppDashboardSalesOverviewRoute: typeof AppDashboardSalesOverviewRoute
  AppDashboardScannerTransactionsRoute: typeof AppDashboardScannerTransactionsRoute
  AppDashboardScanningRoute: typeof AppDashboardScanningRoute
  AppDashboardShippingCompaniesRoute: typeof AppDashboardShippingCompaniesRoute
  AppDashboardShippingOverviewRoute: typeof AppDashboardShippingOverviewRoute
  AppDashboardShippingReturnsRoute: typeof AppDashboardShippingReturnsRoute
  AppDashboardStockCountsRoute: typeof AppDashboardStockCountsRoute
  AppDashboardStockOperationsRoute: typeof AppDashboardStockOperationsRoute
  AppDashboardStorageLocationsRoute: typeof AppDashboardStorageLocationsRoute
  AppDashboardStoresRoute: typeof AppDashboardStoresRoute
  AppDashboardSupplierOverviewRoute: typeof AppDashboardSupplierOverviewRoute
  AppDashboardSyncErrorsRoute: typeof AppDashboardSyncErrorsRoute
  AppDashboardUomRoute: typeof AppDashboardUomRoute
  AppDashboardVendorsRoute: typeof AppDashboardVendorsRoute
  AppDashboardWarehousesRoute: typeof AppDashboardWarehousesRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppChangePasswordRoute: AppChangePasswordRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSystemSettingsRoute: AppSystemSettingsRoute,
  AppTestRoute: AppTestRoute,
  AppUsersRoute: AppUsersRoute,
  AppDashboardAccountingOverviewRoute: AppDashboardAccountingOverviewRoute,
  AppDashboardAddBatchRoute: AppDashboardAddBatchRoute,
  AppDashboardAddInventoryTransactionRoute:
    AppDashboardAddInventoryTransactionRoute,
  AppDashboardAddProductRoute: AppDashboardAddProductRoute,
  AppDashboardAddSaleRoute: AppDashboardAddSaleRoute,
  AppDashboardAlertsRoute: AppDashboardAlertsRoute,
  AppDashboardApiKeysRoute: AppDashboardApiKeysRoute,
  AppDashboardAppsRoute: AppDashboardAppsRoute,
  AppDashboardBrandsRoute: AppDashboardBrandsRoute,
  AppDashboardCategoriesRoute: AppDashboardCategoriesRoute,
  AppDashboardCitiesRoute: AppDashboardCitiesRoute,
  AppDashboardCompanyRoute: AppDashboardCompanyRoute,
  AppDashboardConfirmationOverviewRoute: AppDashboardConfirmationOverviewRoute,
  AppDashboardConsignmentVendorsRoute: AppDashboardConsignmentVendorsRoute,
  AppDashboardCouponsRoute: AppDashboardCouponsRoute,
  AppDashboardCustomersRoute: AppDashboardCustomersRoute,
  AppDashboardDeficitsAlertRoute: AppDashboardDeficitsAlertRoute,
  AppDashboardDirectoryRoute: AppDashboardDirectoryRoute,
  AppDashboardFulfillmentListsRoute: AppDashboardFulfillmentListsRoute,
  AppDashboardGovernoratesRoute: AppDashboardGovernoratesRoute,
  AppDashboardIntegrationsRoute: AppDashboardIntegrationsRoute,
  AppDashboardInventoryAdjustmentRoute: AppDashboardInventoryAdjustmentRoute,
  AppDashboardInventoryOverviewRoute: AppDashboardInventoryOverviewRoute,
  AppDashboardInventoryTransactionsRoute:
    AppDashboardInventoryTransactionsRoute,
  AppDashboardInventoryTransfersRoute: AppDashboardInventoryTransfersRoute,
  AppDashboardLowStockRoute: AppDashboardLowStockRoute,
  AppDashboardOperationTypesRoute: AppDashboardOperationTypesRoute,
  AppDashboardOrderSourcesRoute: AppDashboardOrderSourcesRoute,
  AppDashboardOrdersRoute: AppDashboardOrdersRouteWithChildren,
  AppDashboardOrdersTransactionsRoute: AppDashboardOrdersTransactionsRoute,
  AppDashboardPackingListRoute: AppDashboardPackingListRoute,
  AppDashboardPaymentMethodsRoute: AppDashboardPaymentMethodsRoute,
  AppDashboardPickingListRoute: AppDashboardPickingListRoute,
  AppDashboardProductFamilyRoute: AppDashboardProductFamilyRoute,
  AppDashboardProductStocksRoute: AppDashboardProductStocksRoute,
  AppDashboardProductionRoute: AppDashboardProductionRoute,
  AppDashboardProductsRoute: AppDashboardProductsRoute,
  AppDashboardPurchaseOrdersRoute: AppDashboardPurchaseOrdersRoute,
  AppDashboardPurchaseTransactionsRoute: AppDashboardPurchaseTransactionsRoute,
  AppDashboardReasonsRoute: AppDashboardReasonsRoute,
  AppDashboardReportsRoute: AppDashboardReportsRouteWithChildren,
  AppDashboardReturnsRoute: AppDashboardReturnsRoute,
  AppDashboardSalesOverviewRoute: AppDashboardSalesOverviewRoute,
  AppDashboardScannerTransactionsRoute: AppDashboardScannerTransactionsRoute,
  AppDashboardScanningRoute: AppDashboardScanningRoute,
  AppDashboardShippingCompaniesRoute: AppDashboardShippingCompaniesRoute,
  AppDashboardShippingOverviewRoute: AppDashboardShippingOverviewRoute,
  AppDashboardShippingReturnsRoute: AppDashboardShippingReturnsRoute,
  AppDashboardStockCountsRoute: AppDashboardStockCountsRoute,
  AppDashboardStockOperationsRoute: AppDashboardStockOperationsRoute,
  AppDashboardStorageLocationsRoute: AppDashboardStorageLocationsRoute,
  AppDashboardStoresRoute: AppDashboardStoresRoute,
  AppDashboardSupplierOverviewRoute: AppDashboardSupplierOverviewRoute,
  AppDashboardSyncErrorsRoute: AppDashboardSyncErrorsRoute,
  AppDashboardUomRoute: AppDashboardUomRoute,
  AppDashboardVendorsRoute: AppDashboardVendorsRoute,
  AppDashboardWarehousesRoute: AppDashboardWarehousesRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PlatformRouteRouteChildren {
  PlatformPlatformCompaniesRoute: typeof PlatformPlatformCompaniesRoute
  PlatformPlatformIndexRoute: typeof PlatformPlatformIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformPlatformCompaniesRoute: PlatformPlatformCompaniesRoute,
  PlatformPlatformIndexRoute: PlatformPlatformIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicImpersonationRoute: typeof PublicImpersonationRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicImpersonationRoute: PublicImpersonationRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ApiPublicProxySplatRoute: ApiPublicProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
